# Generated by Django 4.2.7 on 2024-01-04 13:34

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_litteruser_following_alter_litteruser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litteruser',
            options={},
        ),
        migrations.AlterField(
            model_name='litteruser',
            name='usertag',
            field=models.CharField(error_messages={'unique': 'A user with that usertag already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='usertag'),
        ),
        migrations.AddIndex(
            model_name='litteruser',
            index=models.Index(fields=['usertag'], name='litteruser_usertag_idx'),
        ),
    ]
